apiVersion: v1
kind: Service
metadata:
  name: etcd-backup-metrics-collector
  namespace: kube-system
  labels:
    app: etcd-backup
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: etcd-backup
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-backup-metrics-exporter
  namespace: kube-system
  labels:
    app: etcd-backup
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
    - port: 2112
  selector:
    app: etcd-backup

