apiVersion: v1
kind: Service
metadata:
  name: etcd-backup-metrics
  namespace: kube-system
  labels:
    app: etcd-backup
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
    - port: 8080
    - port: 2112
  selector:
    app: etcd-backup

